/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Pancake-Q",
  "description": "Pancake-Q 知识沉淀",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-177215ce",
      "path": "/"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "Pancake-Q",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/mqyqingfeng"
          },
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/712139234359182/posts"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}